spring.application.name=be_demo_angular

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/todo_db_angular
spring.datasource.username=user_angular
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
